apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram-alerts
    group_by:
      - alertname
      - service
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    matchers:
      - severity = "critical"

  - orgId: 1
    receiver: discord-alerts
    group_by:
      - alertname
      - service
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    matchers:
      - severity = "warning"

  - orgId: 1
    receiver: default
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h

  - orgId: 1
    receiver: default